# importing Libraries

In [1]:
import numpy as np
import pandas as pd

# Loading the datasets from sklearn

In [2]:
from sklearn.datasets import load_wine
wine=load_wine()
x=wine.data
y=wine.target

# Split the datasets

In [3]:
from sklearn.model_selection import train_test_split as tts
train_x,test_x,train_y,test_y=tts(x,y,test_size=0.2)

# import sklearn libraries

In [4]:
from sklearn.svm import SVC
from sklearn.metrics import r2_score as rs, confusion_matrix as cm, classification_report as cr

# Linear

In [5]:
Linear = SVC(kernel = 'linear', degree = 8)
Linear.fit(train_x, train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
pred_linear=Linear.predict(test_x)
result=pd.DataFrame({'Actual':test_y,'Predicted':pred_linear})
print(result)

    Actual  Predicted
0        0          0
1        1          0
2        1          1
3        1          0
4        0          0
5        0          0
6        1          1
7        1          1
8        0          0
9        2          2
10       1          1
11       2          2
12       0          0
13       1          1
14       2          2
15       1          0
16       2          2
17       1          1
18       0          0
19       0          0
20       1          1
21       0          0
22       0          0
23       2          2
24       0          0
25       0          0
26       2          2
27       0          0
28       1          1
29       1          1
30       0          0
31       1          1
32       2          2
33       0          0
34       1          1
35       1          1


In [7]:
print(rs(test_y,pred_linear)*100)

84.72418670438473


In [8]:
print(cm(test_y,pred_linear))

[[14  0  0]
 [ 3 12  0]
 [ 0  0  7]]


In [9]:
print(cr(test_y,pred_linear))

             precision    recall  f1-score   support

          0       0.82      1.00      0.90        14
          1       1.00      0.80      0.89        15
          2       1.00      1.00      1.00         7

avg / total       0.93      0.92      0.92        36



# Poly

In [10]:
Poly = SVC(kernel = 'poly', degree = 8)
Poly.fit(train_x, train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
pred_poly=Poly.predict(test_x)
result=pd.DataFrame({'Actual':test_y,'Predicted':pred_poly})
print(result)

    Actual  Predicted
0        0          1
1        1          1
2        1          1
3        1          1
4        0          1
5        0          1
6        1          1
7        1          1
8        0          1
9        2          2
10       1          1
11       2          2
12       0          1
13       1          1
14       2          2
15       1          1
16       2          1
17       1          1
18       0          2
19       0          1
20       1          1
21       0          1
22       0          1
23       2          2
24       0          1
25       0          1
26       2          2
27       0          1
28       1          1
29       1          1
30       0          1
31       1          1
32       2          2
33       0          2
34       1          1
35       1          1


In [12]:
print(rs(test_y,pred_poly)*100)

-6.930693069306915


In [13]:
print(cm(test_y,pred_poly))

[[ 0 12  2]
 [ 0 15  0]
 [ 0  1  6]]


In [14]:
print(cr(test_y,pred_poly))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        14
          1       0.54      1.00      0.70        15
          2       0.75      0.86      0.80         7

avg / total       0.37      0.58      0.45        36



C:\Users\mikkujain\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Gaussian

In [15]:
model_Gaussian = SVC(kernel = 'rbf', degree = 8)
model_Gaussian.fit(train_x, train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
pred_gaussian=model_Gaussian.predict(test_x)
result=pd.DataFrame({'Prediction':pred_gaussian,'Actual':test_y})
print(result)

    Actual  Prediction
0        0           1
1        1           1
2        1           1
3        1           1
4        0           1
5        0           1
6        1           1
7        1           1
8        0           1
9        2           1
10       1           1
11       2           1
12       0           0
13       1           1
14       2           1
15       1           1
16       2           1
17       1           1
18       0           1
19       0           1
20       1           1
21       0           1
22       0           1
23       2           1
24       0           0
25       0           1
26       2           2
27       0           1
28       1           1
29       1           1
30       0           1
31       1           1
32       2           1
33       0           1
34       1           1
35       1           1


In [17]:
print(cr(test_y,pred_gaussian))

             precision    recall  f1-score   support

          0       1.00      0.14      0.25        14
          1       0.45      1.00      0.62        15
          2       1.00      0.14      0.25         7

avg / total       0.77      0.50      0.41        36



In [18]:
print(cm(test_y,pred_gaussian))

[[ 2 12  0]
 [ 0 15  0]
 [ 0  6  1]]


In [19]:
print(rs(test_y,pred_gaussian)*100)

8.345120226308367


# Sigmoid

In [20]:
model_Sigmoid = SVC(kernel = 'sigmoid', degree = 8)
model_Sigmoid.fit(train_x,train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
prediction_Sigmoid=model_Sigmoid.predict(test_x)

results_Sigmoid=pd.DataFrame({'Prediction':prediction_Sigmoid,'Actual':test_y})
print(results_Sigmoid)

    Actual  Prediction
0        0           1
1        1           1
2        1           1
3        1           1
4        0           1
5        0           1
6        1           1
7        1           1
8        0           1
9        2           1
10       1           1
11       2           1
12       0           1
13       1           1
14       2           1
15       1           1
16       2           1
17       1           1
18       0           1
19       0           1
20       1           1
21       0           1
22       0           1
23       2           1
24       0           1
25       0           1
26       2           1
27       0           1
28       1           1
29       1           1
30       0           1
31       1           1
32       2           1
33       0           1
34       1           1
35       1           1


In [22]:
print(cr(test_y,prediction_Sigmoid))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        14
          1       0.42      1.00      0.59        15
          2       0.00      0.00      0.00         7

avg / total       0.17      0.42      0.25        36



In [23]:
print(cm(test_y,prediction_Sigmoid))

[[ 0 14  0]
 [ 0 15  0]
 [ 0  7  0]]


In [24]:
print(rs(test_y,prediction_Sigmoid)*100)

-6.930693069306915
