# What is the probability of a person playing when the weather is sunny? Find P(Yes|Sunny).
                        
                                            Weather	Play
                                            Sunny	No
                                            Overcast	Yes
                                            Rainy	Yes
                                            Sunny	Yes
                                            Sunny	Yes
                                            Overcast	Yes
                                            Rainy	No
                                            Rainy	No
                                            Sunny	Yes
                                            Rainy	Yes
                                            Sunny	No
                                            Overcast	Yes
                                            Overcast	Yes
                                            Rainy	No

In [3]:
# probality of play yes when the whether is sunny
sunny1=2
# probality of play no when the whether is sunny
sunny2=2
# probality of play yes when the whether is Overcast
overcast1=4
# probality of play no when the whether is Overcast
overcast2=0
# probality of play yes when the whether is Rainy
rainy1=2
# probality of play no when the whether is Rainy
rainy2=3
Total_yes=8
Total_no=5

#prbaility i.e p(Yes|Sunny)
A=sunny1/Total_yes
print("P(Yes|Sunny)=",A)



P(Yes|Sunny)= 0.25


# importing Libraries

In [7]:
import numpy as np
import pandas as pd

# Load datasets iris from sklearn

In [2]:
from sklearn.datasets import load_iris
data=load_iris()
x=data['data']
y=data['target']

In [17]:
from sklearn.model_selection import train_test_split as tts
train_x, test_x, train_y, test_y = tts(x, y, test_size = 0.2)

In [18]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_x, train_y)

GaussianNB(priors=None)

In [19]:
ypred = gnb.predict(test_x)

In [20]:
result=pd.DataFrame({'Actual':test_y,'Predicted':ypred})
print(result)

    Actual  Predicted
0        1          1
1        1          1
2        1          1
3        0          0
4        0          0
5        1          1
6        2          2
7        0          0
8        1          1
9        1          1
10       1          1
11       1          1
12       2          2
13       0          0
14       1          1
15       2          2
16       0          0
17       2          2
18       1          1
19       0          0
20       0          0
21       2          2
22       0          0
23       2          1
24       1          2
25       2          2
26       2          2
27       1          1
28       2          2
29       0          0


In [21]:
from sklearn.metrics import classification_report as cr, confusion_matrix as cm, r2_score as rs
print(cr(y_test,ypred))

             precision    recall  f1-score   support

          0       0.44      0.40      0.42        10
          1       0.33      0.44      0.38         9
          2       0.44      0.36      0.40        11

avg / total       0.41      0.40      0.40        30



In [22]:
print(cm(y_test,ypred))

[[4 4 2]
 [2 4 3]
 [3 4 4]]


In [31]:
print(rs(y_test,ypred)*100)

-57.39268680445153


# MNB

In [24]:
from sklearn.naive_bayes import MultinomialNB
model_MNB=MultinomialNB()

model_MNB.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [25]:
prediction_MNB=model_MNB.predict(test_x)

In [26]:
results_MNB=pd.DataFrame({'Prediction':prediction_MNB,'Actual':test_y})
print(results_MNB)

    Actual  Prediction
0        1           1
1        1           2
2        1           1
3        0           0
4        0           0
5        1           2
6        2           2
7        0           0
8        1           1
9        1           1
10       1           2
11       1           1
12       2           2
13       0           0
14       1           1
15       2           2
16       0           0
17       2           2
18       1           2
19       0           0
20       0           0
21       2           2
22       0           0
23       2           2
24       1           2
25       2           2
26       2           2
27       1           1
28       2           2
29       0           0


In [27]:
print(cr(test_y,prediction_MNB))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      0.58      0.74        12
          2       0.64      1.00      0.78         9

avg / total       0.89      0.83      0.83        30



In [29]:
print(cm(test_y,prediction_MNB))

[[9 0 0]
 [0 7 5]
 [0 0 9]]


In [30]:
print(rs(test_y,prediction_MNB)*100)

72.22222222222221
